-- keybinding helper
vim.pack.add({ "https://github.com/echasnovski/mini.nvim" }, { confirm = false })

local miniclue = require("mini.clue")
miniclue.setup({
  triggers = {
    { mode = "n", keys = "<Leader>" },
    { mode = "x", keys = "<Leader>" },
    { mode = "n", keys = "g" },
    { mode = "x", keys = "g" },
    { mode = "n", keys = "'" },
    { mode = "x", keys = "'" },
    { mode = "n", keys = "`" },
    { mode = "x", keys = "`" },
    { mode = "n", keys = '"' },
    { mode = "x", keys = '"' },
    { mode = "i", keys = "<C-r>" },
    { mode = "c", keys = "<C-r>" },
    { mode = "n", keys = "<C-w>" },
    { mode = "n", keys = "z" },
    { mode = "x", keys = "z" },
    { mode = "n", keys = "[" },
    { mode = "n", keys = "]" },
  },
  clues = {
    { mode = "n", keys = "<Leader>c", desc = "+[C]ode" },
    { mode = "n", keys = "<Leader>s", desc = "+[S]earch" },
    { mode = "n", keys = "<Leader>u", desc = "+[U]I" },
    { mode = "n", keys = "<Leader>g", desc = "+[G]it" },
    { mode = "n", keys = "<Leader>9", desc = "+[9]9 (AI assist)" },
    { mode = "n", keys = "<Leader>b", desc = "+[B]uffer" },
    { mode = "n", keys = "<Leader>d", desc = "+[D]iagnostics" },
    { mode = "n", keys = "<Leader>f", desc = "+[F]ind/replace" },
    { mode = "v", keys = "<Leader>f", desc = "+[F]ind/replace" },
    { mode = "n", keys = "<Leader>p", desc = "+Debug [P]rint" },
    { mode = "x", keys = "<Leader>p", desc = "+Debug [P]rint" },
    { mode = "n", keys = "<Leader>q", desc = "+[Q]uickfix" },
    { mode = "n", keys = "<Leader>r", desc = "+[R]efactor" },
    { mode = "x", keys = "<Leader>r", desc = "+[R]efactor" },
    { mode = "n", keys = "<Leader>t", desc = "+[T]ab/split" },
    miniclue.gen_clues.builtin_completion(),
    miniclue.gen_clues.g(),
    miniclue.gen_clues.marks(),
    miniclue.gen_clues.registers(),
    miniclue.gen_clues.windows(),
    miniclue.gen_clues.z(),
  },
  window = {
    delay = 300,
    config = { width = 60 },
  },
})
