onboarding = false

[keys]
prefix = "cmd+h"
focus_pane_left = ["prefix+left"]
focus_pane_down = ["prefix+j", "prefix+down"]
focus_pane_up = ["prefix+k", "prefix+up"]
focus_pane_right = ["prefix+l", "prefix+right"]
previous_tab = "cmd+["
next_tab = "cmd+]"
previous_workspace = "cmd+up"
next_workspace = "cmd+down"
switch_workspace = "cmd+1..9"
rename_tab = "cmd+r"

[theme]
name = "terminal"
auto_switch = false

[ui.toast]
delivery = "herdr"

[ui]
show_agent_labels_on_pane_borders = true
pane_borders = true
pane_gaps = true
sidebar_collapsed_mode = "hidden"

agent_panel_sort = "spaces"
[theme.custom]
panel_bg = "#1a2024"
surface_dim = "#3a444c"

[[keys.command]]
key = "prefix+h"
type = "plugin_action"
command = "beyondlex.herdr-recent-navigator.focus-workspaces"
description = "Open Navigator: Workspace"

[[keys.command]]
key = "prefix+a"
type = "plugin_action"
command = "beyondlex.herdr-recent-navigator.focus-agents"
description = "Open Navigator: Agents"

[[keys.command]]
key = "prefix+t"
type = "plugin_action"
command = "herdr-navigator.open"
description = "jump to anything"
