vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.background = "light"
vim.g.colors_name = "james"

local bg = "#F8EFE7"
local bg_cursorline = "#EFE5DC"
local bg_float = "#E8DCCC"
local fg = "#000000"
local blue = "#2573B6"
local tan = "#C49D7B"
local green_bg = "#D6F5B3"
local red_bg = "#FFB6B6"
local orange_bg = "#FFCBA8"
local blue_bg = "#C8E4F5"
local purple_bg = "#E5D0F0"
local yellow_bg = "#FFF2A8"
local green = "#218871"
local purple = "#8D44AC"
local red = "#D32F2F"

local set = vim.api.nvim_set_hl

-- editor
set(0, "Normal", { fg = fg, bg = bg })
set(0, "NormalNC", { fg = fg, bg = bg })
set(0, "NormalFloat", { fg = fg, bg = bg_float })
set(0, "FloatBorder", { fg = fg, bg = bg_float })
set(0, "EndOfBuffer", { fg = bg, bg = bg })
set(0, "SignColumn", { fg = fg, bg = bg })
set(0, "LineNr", { fg = fg, bg = bg })
set(0, "CursorLineNr", { fg = fg, bg = bg_cursorline, bold = true })
set(0, "CursorLine", { bg = bg_cursorline })
set(0, "ColorColumn", { bg = bg })
set(0, "VertSplit", { fg = fg, bg = bg })
set(0, "WinSeparator", { fg = fg, bg = bg })
set(0, "StatusLine", { fg = fg, bg = bg })
set(0, "StatusLineNC", { fg = fg, bg = bg })
set(0, "TabLine", { fg = fg, bg = bg })
set(0, "TabLineFill", { fg = fg, bg = bg })
set(0, "TabLineSel", { fg = fg, bg = bg, bold = true })
set(0, "Pmenu", { fg = fg, bg = bg })
set(0, "PmenuSel", { fg = fg, bg = bg, reverse = true })
set(0, "PmenuSbar", { bg = bg })
set(0, "PmenuThumb", { bg = fg })
set(0, "Visual", { bg = bg, reverse = true })
set(0, "Search", { fg = fg, bg = bg, reverse = true })
set(0, "IncSearch", { fg = fg, bg = bg, reverse = true })
set(0, "CurSearch", { fg = fg, bg = bg, reverse = true })
set(0, "MatchParen", { fg = fg, bg = bg, bold = true })
set(0, "Folded", { fg = fg, bg = bg })
set(0, "FoldColumn", { fg = fg, bg = bg })
set(0, "Cursor", { fg = bg, bg = fg })
set(0, "NonText", { fg = fg })
set(0, "Whitespace", { fg = fg })
set(0, "SpecialKey", { fg = fg })
set(0, "Directory", { fg = fg })
set(0, "Title", { fg = fg, bold = true })
set(0, "ErrorMsg", { fg = fg, bg = bg })
set(0, "WarningMsg", { fg = fg, bg = bg })
set(0, "ModeMsg", { fg = fg, bg = bg })
set(0, "MoreMsg", { fg = fg, bg = bg })
set(0, "Question", { fg = fg, bg = bg })
set(0, "WildMenu", { fg = fg, bg = bg, reverse = true })
set(0, "Conceal", { fg = fg, bg = bg })

-- syntax (legacy vim groups)
set(0, "Comment", { fg = tan, italic = true })
set(0, "Constant", { fg = fg })
set(0, "String", { fg = fg, bg = green_bg })
set(0, "Character", { fg = fg, bg = green_bg })
set(0, "Number", { fg = fg, bg = orange_bg })
set(0, "Boolean", { fg = fg, bg = yellow_bg })
set(0, "Float", { fg = fg, bg = orange_bg })
set(0, "Identifier", { fg = fg })
set(0, "Function", { fg = blue })
set(0, "Statement", { fg = fg })
set(0, "Conditional", { fg = fg, bg = blue_bg, bold = true })
set(0, "Repeat", { fg = fg, bg = blue_bg, bold = true })
set(0, "Label", { fg = fg })
set(0, "Operator", { fg = fg })
set(0, "Keyword", { fg = fg })
set(0, "Exception", { fg = fg })
set(0, "PreProc", { fg = fg })
set(0, "Include", { fg = fg })
set(0, "Define", { fg = fg })
set(0, "Macro", { fg = fg })
set(0, "PreCondit", { fg = fg })
set(0, "Type", { fg = purple })
set(0, "StorageClass", { fg = purple })
set(0, "Structure", { fg = purple })
set(0, "Typedef", { fg = purple })
set(0, "Special", { fg = fg })
set(0, "SpecialChar", { fg = fg })
set(0, "Tag", { fg = fg })
set(0, "Delimiter", { fg = fg })
set(0, "SpecialComment", { fg = fg })
set(0, "Debug", { fg = fg })
set(0, "Underlined", { fg = fg, underline = true })
set(0, "Ignore", { fg = fg })
set(0, "Error", { fg = fg, bg = bg })
set(0, "Todo", { fg = fg, bg = bg, bold = true })

-- treesitter
set(0, "@variable", { fg = fg })
set(0, "@variable.builtin", { fg = fg })
set(0, "@variable.parameter", { fg = fg })
set(0, "@variable.member", { fg = fg })
set(0, "@constant", { fg = fg })
set(0, "@constant.builtin", { fg = fg })
set(0, "@module", { fg = fg })
set(0, "@string", { fg = fg, bg = green_bg })
set(0, "@string.escape", { fg = fg, bg = green_bg })
set(0, "@character", { fg = fg, bg = green_bg })
set(0, "@number", { fg = fg, bg = orange_bg })
set(0, "@number.float", { fg = fg, bg = orange_bg })
set(0, "@boolean", { fg = fg, bg = yellow_bg })
set(0, "@function", { fg = blue })
set(0, "@function.call", { fg = blue })
set(0, "@function.builtin", { fg = blue })
set(0, "@function.method", { fg = blue })
set(0, "@function.method.call", { fg = blue })
set(0, "@constructor", { fg = fg, bold = true })
set(0, "@constructor.tsx", { fg = fg, bold = true })
set(0, "@tag.tsx", { fg = fg, bold = true })
set(0, "@operator", { fg = fg })
set(0, "@keyword", { fg = fg })
set(0, "@keyword.function", { fg = fg })
set(0, "@keyword.return", { fg = fg, bg = purple_bg, bold = true })
set(0, "@keyword.conditional", { fg = fg, bg = blue_bg, bold = true })
set(0, "@conditional", { fg = fg, bg = blue_bg, bold = true })
set(0, "@keyword.repeat", { fg = fg, bg = blue_bg, bold = true })
set(0, "@repeat", { fg = fg, bg = blue_bg, bold = true })
set(0, "@keyword.import", { fg = fg })
set(0, "@type", { fg = purple })
set(0, "@type.builtin", { fg = purple })
set(0, "@property", { fg = fg })
set(0, "@punctuation", { fg = fg })
set(0, "@punctuation.bracket", { fg = fg })
set(0, "@punctuation.delimiter", { fg = fg })
set(0, "@tag", { fg = fg })
set(0, "@tag.attribute", { fg = fg })
set(0, "@tag.delimiter", { fg = fg })
set(0, "@comment", { fg = tan, italic = true })

-- lsp semantic tokens
set(0, "@lsp.type.class", { fg = purple })
set(0, "@lsp.type.function", { fg = blue })
set(0, "@lsp.type.method", { fg = blue })
set(0, "@lsp.type.variable", { fg = fg })
set(0, "@lsp.type.parameter", { fg = fg })
set(0, "@lsp.type.property", { fg = fg })
set(0, "@lsp.type.type", { fg = purple })
set(0, "@lsp.type.interface", { fg = purple })
set(0, "@lsp.type.enum", { fg = purple })
set(0, "@lsp.type.namespace", { fg = fg })
set(0, "@lsp.typemod.variable.declaration", { fg = fg, italic = true })
set(0, "@lsp.typemod.variable.definition", { fg = fg, italic = true })
set(0, "@lsp.typemod.function.declaration", { fg = blue, bold = true })
set(0, "@lsp.typemod.function.definition", { fg = blue, bold = true })
set(0, "@lsp.typemod.method.declaration", { fg = blue, bold = true })
set(0, "@lsp.typemod.method.definition", { fg = blue, bold = true })

-- diagnostics
set(0, "DiagnosticError", { fg = fg, bg = red_bg })
set(0, "DiagnosticVirtualTextError", { fg = fg, bg = red_bg })
set(0, "DiagnosticSignError", { fg = fg, bg = red_bg })
set(0, "DiagnosticWarn", { fg = fg, bg = orange_bg })
set(0, "DiagnosticVirtualTextWarn", { fg = fg, bg = orange_bg })
set(0, "DiagnosticSignWarn", { fg = fg, bg = orange_bg })
set(0, "DiagnosticInfo", { fg = fg })
set(0, "DiagnosticHint", { fg = fg })
set(0, "DiagnosticOk", { fg = fg })
set(0, "DiagnosticUnderlineError", { undercurl = true, sp = red })
set(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = fg })
set(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = fg })
set(0, "DiagnosticUnderlineHint", { undercurl = true, sp = fg })

-- git signs
set(0, "DiffAdd", { fg = fg, bg = bg })
set(0, "DiffChange", { fg = fg, bg = bg })
set(0, "DiffDelete", { fg = fg, bg = bg })
set(0, "DiffText", { fg = fg, bg = bg, bold = true })
